// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnQ2121grEhKYwz2XigNKvCXEPMWJP2U',
    appId: '1:549688103376:web:388f804883f75269ca29d5',
    messagingSenderId: '549688103376',
    projectId: 'soundify-b7297',
    authDomain: 'soundify-b7297.firebaseapp.com',
    storageBucket: 'soundify-b7297.appspot.com',
    measurementId: 'G-JEH95M2RX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQS1ix6HWch2fkSzwdsmS1fa9T2DzWBk',
    appId: '1:549688103376:android:80f606fb3c79984aca29d5',
    messagingSenderId: '549688103376',
    projectId: 'soundify-b7297',
    storageBucket: 'soundify-b7297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxmO6VgEybU7N8f1L0c0v2ik3hP4dC10',
    appId: '1:549688103376:ios:473855184a4db78fca29d5',
    messagingSenderId: '549688103376',
    projectId: 'soundify-b7297',
    storageBucket: 'soundify-b7297.appspot.com',
    iosBundleId: 'com.example.sounantStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrxmO6VgEybU7N8f1L0c0v2ik3hP4dC10',
    appId: '1:549688103376:ios:473855184a4db78fca29d5',
    messagingSenderId: '549688103376',
    projectId: 'soundify-b7297',
    storageBucket: 'soundify-b7297.appspot.com',
    iosBundleId: 'com.example.sounantStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYnQ2121grEhKYwz2XigNKvCXEPMWJP2U',
    appId: '1:549688103376:web:524dbfddfd7c24b1ca29d5',
    messagingSenderId: '549688103376',
    projectId: 'soundify-b7297',
    authDomain: 'soundify-b7297.firebaseapp.com',
    storageBucket: 'soundify-b7297.appspot.com',
    measurementId: 'G-YLPW3LJVKF',
  );
}